### ISSUE TITLE
ClassCastException for AdaptiveIconDrawable to BitmapDrawable

### ISSUE THREAD

**Issue by tialawllol** [googleads/googleads-consent-sdk-android#2] opened 2018-05-21 21:51 UTC
`05-21 21:50:04.859 18303-18303/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 
    java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
        at com.google.ads.consent.ConsentForm.getAppIconURIString(ConsentForm.java:219)
        at com.google.ads.consent.ConsentForm.updateDialogContent(ConsentForm.java:237)
        at com.google.ads.consent.ConsentForm.access$900(ConsentForm.java:45)
        at com.google.ads.consent.ConsentForm$2.onPageFinished(ConsentForm.java:147)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by frankyxcs** [comment] 2018-05-21 22:27
yes i have this bug too 


                    android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable


Reason could be "But since Android 8.0 you can set an adaptive icon, which is not a bitmap, thus the App Theme Engine crashes on it."

see also 
                    https://stackoverflow.com/questions/50077917/android-graphics-drawable-adaptiveicondrawable-cannot-be-cast-to-android-graphic

**Comment by rampara** [comment] 2018-05-22 00:10
@frankyxcs @tialawllol this crash does seem to be caused by `AdaptiveIconDrawable` failing to cast to `Bitmap`. Will be fixed in a future release but as a workaround you can update the `getAppIconURIString()` method of `ConsentForm` to the following:

```
private static String getAppIconURIString(Context context) {
        Drawable iconDrawable = context.getPackageManager().getApplicationIcon(context
            .getApplicationInfo());
        Bitmap bitmap = Bitmap.createBitmap(iconDrawable.getIntrinsicWidth(),
            iconDrawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
        final Canvas canvas = new Canvas(bitmap);
        iconDrawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        iconDrawable.draw(canvas);
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, byteArrayOutputStream);
        byte[] byteArray = byteArrayOutputStream.toByteArray();
        return "data:image/png;base64," + Base64.encodeToString(byteArray, Base64.DEFAULT);
    }
```

**Comment by Mirkoddd** [comment] 2018-05-22 17:41
@rampara  in the meantime I can also choose to implement a custom dialog, right?

**Comment by rampara** [comment] 2018-05-22 18:21
@Mirkoddd yes. choosing to collect consent yourself and forwarding consent status to the Consent SDK is always an alternative.

**Comment by olivierbernal** [comment] 2018-05-24 01:18
@rampara: Thanks for this fix. When do you plan to push it to gradle?

**Comment by rampara** [comment] 2018-05-24 23:59
Just pushed v1.0.2 to gMaven.

**Closed** 2018-05-25 00:00 UTC
Labels: bug
