### ISSUE TITLE
Again Tons of TGKILL or Signal 11 crashes

### ISSUE THREAD

**Issue by frankyxcs** [googleads/googleads-consent-sdk-android#62] opened 2018-06-02 20:40 UTC
it is really bad  at the moment and it seems that the consent sdk has a lot of heavy bugs. After 5 days of running i have tons of crashes like this . I hope you fix it asap !

crashes are mostly on 4.1,4.2,4.4 phones and the rest up to android 8

backtrace:
  #00  pc 0000000000071844  /system/lib64/libc.so (tgkill+8)
  #01  pc 000000000001e058  /system/lib64/libc.so (abort+88)
  #02  pc 0000000000943070  /data/app/com.android.chrome-BOahEP1enjbHuqIYJ7_42g==/base.apk

backtrace:
  #00  pc 0000000000194ad0  /system/lib/libwebviewchromium.so
  #01  pc 0000000000020e0c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
  #02  pc 0000000000051aaf  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
  #03  pc 000000000002a2a0  /system/lib/libdvm.so
  #04  pc 0000000000031750  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
  #05  pc 000000000002ede8  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
  #06  pc 0000000000063f15  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
  #07  pc 0000000000050815  /system/lib/libdvm.so
  #08  pc 0000000000194c8d  /system/lib/libwebviewchromium.so
  #09  pc 000000000019577b  /system/lib/libwebviewchromium.so
  #10  pc 000000000018cc2b  /system/lib/libwebviewchromium.so
  #11  pc 000000000018e5a9  /system/lib/libwebviewchromium.so
  #12  pc 000000000018c5e9  /system/lib/libwebviewchromium.so
  #13  pc 00000000002d0e15  /system/lib/libwebviewchromium.so
  #14  pc 00000000002d24d9  /system/lib/libwebviewchromium.so
  #15  pc 00000000002d0b03  /system/lib/libwebviewchromium.so
  #16  pc 00000000002d11f3  /system/lib/libwebviewchromium.so
  #17  pc 000000000033a75d  /system/lib/libwebviewchromium.so
  #18  pc 00000000003443af  /system/lib/libwebviewchromium.so
  #19  pc 000000000033faa7  /system/lib/libwebviewchromium.so
  #20  pc 0000000000dd19fb  /system/lib/libwebviewchromium.so
  #21  pc 0000000000b15f13  /system/lib/libwebviewchromium.so
  #22  pc 0000000000b4bbdb  /system/lib/libwebviewchromium.so
  #23  pc 0000000000b457e3  /system/lib/libwebviewchromium.so
  #24  pc 0000000000b44e8d  /system/lib/libwebviewchromium.so
  #25  pc 0000000000b22ad3  /system/lib/libwebviewchromium.so
  #26  pc 0000000000b22b5f  /system/lib/libwebviewchromium.so
  #27  pc 0000000000b2a61f  /system/lib/libwebviewchromium.so
  #28  pc 0000000000b469cd  /system/lib/libwebviewchromium.so
  #29  pc 0000000000b46c61  /system/lib/libwebviewchromium.so
  #30  pc 0000000000b42f4b  /system/lib/libwebviewchromium.so
  #31  pc 0000000000b42b67  /system/lib/libwebviewchromium.so

and so on ......

**Comment by MrAdr68** [comment] 2018-06-04 01:01
me too, after implement consent sdk. Tons of Crash tgkill .
User remove app 2x than before. Revenue reduce 50% in EEA .

**Comment by frankyxcs** [comment] 2018-06-04 02:07
It would be 1000times better in my opinion to use something like an alert dialog combined with a listview or something else to realize this consent form and not a webview dialog window. 

People are using millions of old phones all over the world with old and buggy system libs that where never fixed by google. Thats my opinion . 
And still millions of people are using at least 4.1 - 4.4 at the moment. thats the biggest problem.

**Comment by rampara** [comment] 2018-06-06 00:36
Closing as duplicate of #51.

**Closed by rampara** 2018-06-06 00:36 UTC
