### ISSUE TITLE
NoClassDefFoundError causing crashes in version 1.2

### ISSUE THREAD

**Issue by timlosurdo** [googleads/googleads-consent-sdk-android#44] opened 2018-05-27 06:42 UTC
All occurences happening on **Android 4.2**
```
java.lang.RuntimeException:  
  at android.os.AsyncTask$3.done (AsyncTask.java:299) 
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:352) 
  at java.util.concurrent.FutureTask.setException (FutureTask.java:219) 
  at java.util.concurrent.FutureTask.run (FutureTask.java:239) 
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:230) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:573) 
  at java.lang.Thread.run (Thread.java:856)
Caused by: java.lang.NoClassDefFoundError:  
  at com.google.ads.consent.ConsentData.getSDKPlatformString (ConsentData.java:128) 
  at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground (ConsentInformation.java:262) 
  at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground (ConsentInformation.java:189) 
  at android.os.AsyncTask$2.call (AsyncTask.java:287) 
  at java.util.concurrent.FutureTask.run (FutureTask.java:234)
```

**Comment by Cianid** [comment] 2018-05-28 18:49
I'm confirming this. An error occurs at any device with API <19 because all static methods of java.util.Objects are available above API 19 (Android 4.4.+).

**Comment by qwertyway** [comment] 2018-05-31 11:17
This is a big issue. I've got a lot of crashes like this on android 4

**Comment by rampara** [comment] 2018-06-06 00:34
This issue should be resolved in an upcoming release. Closing as duplicate of #33.

**Closed** 2018-06-06 00:34 UTC
Labels: bug, duplicate
