### ISSUE TITLE
Phone and Storage permissions added

### ISSUE THREAD

**Issue by lakshman5876** [googleads/googleads-consent-sdk-android#16] opened 2018-05-23 02:49 UTC
I see Storage read and write and Phone permissions added 
```
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
IMPLIED from /home/lakshman/Projects/android-projects/GN/src/main/AndroidManifest.xml:2:1-59:12 reason: com.google.android.ads.consent has a targetSdkVersion < 4
uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from /home/lakshman/Projects/android-projects/GN/src/main/AndroidManifest.xml:2:1-59:12 reason: com.google.android.ads.consent has a targetSdkVersion < 4
uses-permission#android.permission.READ_EXTERNAL_STORAGE
IMPLIED from /home/lakshman/Projects/android-projects/GN/src/main/AndroidManifest.xml:2:1-59:12 reason: com.google.android.ads.consent requested WRITE_EXTERNAL_STORAGE

```

**Comment by rampara** [comment] 2018-05-23 21:28
@lakshman5876 closing as duplicate of #13.

**Closed** 2018-05-23 21:28 UTC
Labels: bug, duplicate
